spring:
  application:
    name: stripepayment

stripe:
  secret-key: sk_test_51T9fZHBMsjn45j1Zeb9QIotWA74H0oVlPvHp2PNeeqpFRgtksp
  publishable-key: pk_test_51T9fZHBMsjn45j1ZpQeLwmmbRYWdFe8MxqMgqvqhWhM3BGToj
